{{ config(schema='OLIST_STAGING', tags=['staging']) }}

SELECT
    p.PRODUCT_ID,
    COALESCE(t.PRODUCT_CATEGORY_NAME_ENGLISH, p.PRODUCT_CATEGORY_NAME, 'Unknown') AS PRODUCT_CATEGORY,
    p.PRODUCT_NAME_LENGHT AS PRODUCT_NAME_LENGTH,
    p.PRODUCT_DESCRIPTION_LENGHT AS PRODUCT_DESCRIPTION_LENGTH,
    p.PRODUCT_PHOTOS_QTY,
    p.PRODUCT_WEIGHT_G,
    p.PRODUCT_LENGTH_CM,
    p.PRODUCT_HEIGHT_CM,
    p.PRODUCT_WIDTH_CM
FROM {{ source('olist', 'PRODUCTS_RAW') }} p
LEFT JOIN {{ source('olist', 'CATEGORY_TRANSLATION_RAW') }} t
    ON p.PRODUCT_CATEGORY_NAME = t.PRODUCT_CATEGORY_NAME
WHERE p.PRODUCT_ID IS NOT NULL
