{{ config(schema='OLIST_STAGING', tags=['staging']) }}

SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    TO_TIMESTAMP(ORDER_PURCHASE_TIMESTAMP) AS ORDER_PURCHASE_TIMESTAMP,
    TO_TIMESTAMP(ORDER_APPROVED_AT)        AS ORDER_APPROVED_AT,
    TO_TIMESTAMP(ORDER_DELIVERED_CARRIER_DATE) AS ORDER_DELIVERED_CARRIER_DATE,
    TO_TIMESTAMP(ORDER_DELIVERED_CUSTOMER_DATE) AS ORDER_DELIVERED_CUSTOMER_DATE,
    TO_TIMESTAMP(ORDER_ESTIMATED_DELIVERY_DATE) AS ORDER_ESTIMATED_DELIVERY_DATE,
    DATEDIFF('day',
        TO_TIMESTAMP(ORDER_PURCHASE_TIMESTAMP),
        TO_TIMESTAMP(ORDER_DELIVERED_CUSTOMER_DATE)
    ) AS ACTUAL_DELIVERY_DAYS,
    DATEDIFF('day',
        TO_TIMESTAMP(ORDER_DELIVERED_CUSTOMER_DATE),
        TO_TIMESTAMP(ORDER_ESTIMATED_DELIVERY_DATE)
    ) AS DAYS_EARLY_OR_LATE
FROM {{ source('olist', 'ORDERS_RAW') }}
WHERE ORDER_ID IS NOT NULL
