{{ config(schema='OLIST_STAGING', tags=['staging']) }}

SELECT
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    SELLER_ID,
    TO_TIMESTAMP(SHIPPING_LIMIT_DATE) AS SHIPPING_LIMIT_DATE,
    PRICE,
    FREIGHT_VALUE,
    PRICE + FREIGHT_VALUE AS TOTAL_ITEM_VALUE
FROM {{ source('olist', 'ORDER_ITEMS_RAW') }}
WHERE ORDER_ID IS NOT NULL
