{{ config(schema='OLIST_STAGING', tags=['staging']) }}

SELECT
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_ZIP_CODE_PREFIX,
    INITCAP(CUSTOMER_CITY) AS CUSTOMER_CITY,
    CUSTOMER_STATE
FROM {{ source('olist', 'CUSTOMERS_RAW') }}
WHERE CUSTOMER_ID IS NOT NULL
