{{ config(schema='OLIST_STAGING', tags=['staging']) }}

SELECT
    REVIEW_ID,
    ORDER_ID,
    REVIEW_SCORE,
    REVIEW_COMMENT_TITLE,
    REVIEW_COMMENT_MESSAGE,
    TO_TIMESTAMP(REVIEW_CREATION_DATE) AS REVIEW_CREATION_DATE,
    TO_TIMESTAMP(REVIEW_ANSWER_TIMESTAMP) AS REVIEW_ANSWER_TIMESTAMP
FROM {{ source('olist', 'ORDER_REVIEWS_RAW') }}
WHERE ORDER_ID IS NOT NULL
