{{ config(schema='OLIST_MART', tags=['mart']) }}

SELECT
    PAYMENT_TYPE,
    COUNT(DISTINCT ORDER_ID)        AS TOTAL_ORDERS,
    SUM(PAYMENT_VALUE)              AS TOTAL_VALUE,
    ROUND(AVG(PAYMENT_VALUE), 2)    AS AVG_PAYMENT_VALUE,
    ROUND(AVG(PAYMENT_INSTALLMENTS), 1) AS AVG_INSTALLMENTS,
    ROUND(
        COUNT(DISTINCT ORDER_ID) * 100.0 /
        SUM(COUNT(DISTINCT ORDER_ID)) OVER(), 2
    ) AS PCT_OF_ORDERS
FROM {{ ref('stg_payments') }}
GROUP BY 1
ORDER BY TOTAL_VALUE DESC
