{{ config(schema='OLIST_MART', tags=['mart']) }}

SELECT
    DATE_TRUNC('month', ORDER_PURCHASE_TIMESTAMP) AS ORDER_MONTH,
    COUNT(ORDER_ID)                                AS TOTAL_ORDERS,
    ROUND(AVG(ACTUAL_DELIVERY_DAYS), 1)            AS AVG_DELIVERY_DAYS,
    COUNT(CASE WHEN DAYS_EARLY_OR_LATE >= 0 THEN 1 END) AS ON_TIME_DELIVERIES,
    COUNT(CASE WHEN DAYS_EARLY_OR_LATE < 0 THEN 1 END)  AS LATE_DELIVERIES,
    ROUND(
        COUNT(CASE WHEN DAYS_EARLY_OR_LATE >= 0 THEN 1 END) * 100.0 / COUNT(ORDER_ID),
    2) AS ON_TIME_RATE_PCT
FROM {{ ref('stg_orders') }}
WHERE ORDER_STATUS = 'delivered'
AND ACTUAL_DELIVERY_DAYS IS NOT NULL
GROUP BY 1
ORDER BY 1
